language: node_js
node_js:
- 8
- 10
- 12
env:
  global:
  - secure: YH7Z/ES6xEj+KiN5u0r0IxTvA6UO92PnlSjysNMM+tlKAO1M+fQjb3epyixgHvEldu/+iLe2ciF8jAukGobO1uWcHX7VMxklFyliKLq/xsG5HApQPY5i41xouB3zhrFSF6HWHGCYEPCDO66f0LvUL0P+4bazxSFgCLzb9K0ZC9Y=
after_success:
- npm run coveralls
- npm run docs
deploy:
  provider: pages
  local_dir: ./docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
